# sfm algorithm configure
social_force:
  animation_factor: 5.1
  # only handle pedestrians within `people_distance`
  people_distance: 6.0
  # weights of social force model
  goal_weight: 2.0
  obstacle_weight: 80.0
  social_weight: 15
  group_gaze_weight: 3.0
  group_coh_weight: 2.0
  group_rep_weight: 1.0

# pedestrians setting
pedestrians:
  update_rate: 5
  ped_tracker:
    enable: True
    model: Li2Former
    weight: ckpt_jrdb_ann_drow3_e40.pth
    cfg: ros_drownet.yaml

    # weight: drow_li2former_ckpt_e41_5_5_num_1.pth
    # cfg: ros_li2former.yaml
  ped_property:
    - name: human_0
      pose: 1.0 3.00 1 0 0 0
      velocity: 0.9
      radius: 0.4
      cycle: true
      # time_delay: 5
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 1.0 3.00 1 0 0 0
        goal_point_2: 1.0 -1.00 1 0 0 0
    - name: human_1
      pose: -5 -3.5 1 0 0 0
      velocity: 0.9
      radius: 0.4
      cycle: true
      # time_delay: 5
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: -5 -3.5 1 0 0 0
        goal_point_2: -1 -3.5 1 0 0 0
    - name: human_2
      pose: 0.5 -6 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: true
      # time_delay: 7
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 0.5 -6 1 0 0 0
        goal_point_2: 0.5 -10 0 0 0
    - name: human_3
      pose: 1.5 -3.5 1 0 0 0
      velocity: 1.2
      radius: 0.4
      cycle: true
      # time_delay: 8
      ignore:
        model_1: ground_plane
        model_2: turtlebot3_waffle
      trajectory:
        goal_point_1: 1.5 -3.5 1 0 0 0
        goal_point_2: 5 -3.5 1 0 0 0
    # - name: human_4
    #   pose: 8.96 5.18 1 0 0 0
    #   velocity: 1.2
    #   radius: 0.4
    #   cycle: false
    #   # time_delay: 7
    #   ignore:
    #     model_1: ground_plane
    #     model_2: turtlebot3_waffle
    #   trajectory:
    #     goal_point_1: 8.96 5.18 1 0 0 0
    #     goal_point_3: 1.04 4.82 1 0 0 0
    # - name: human_5
    #   pose: 7.28 1.88 1 0 0 0
    #   velocity: 1.2
    #   radius: 0.4
    #   cycle: false
    #   # time_delay: 8
      # ignore:
      #   model_1: ground_plane
      #   model_2: turtlebot3_waffle
      # trajectory:
      #   goal_point_1: 7.28 1.88 1 0 0 0
      #   goal_point_2: 2.72 8.12 1 0 0 0